{% set version = "3.8.0" %}

package:
  name: lapack
  version: {{ version }}

source:
  fn: lapack-{{ version }}.tgz
  url: http://www.netlib.org/lapack/lapack-{{ version }}.tar.gz
  sha256: deb22cc4a6120bff72621155a9917f485f96ef8319ac074a7afbc68aab88bcf6

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - m2w64-toolchain  # [win]
  run:
    - libgfortran      # [not win]
    - m2w64-gcc-libs   # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/liblapack${SHLIB_EXT}  # [unix]
    - if not exist %LIBRARY_PREFIX%\\lib\\liblapack.a exit 1  # [win]

about:
  home: http://www.netlib.org/lapack
  license: BSD 3-Clause
  summary: Linear Algebra PACKage

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - hadim
    - isuruf
