{% set version = "3.6.1" %}

package:
  name: lapack
  version: {{ version }}

source:
  fn: lapack-{{ version }}.tgz
  url: http://www.netlib.org/lapack/lapack-{{ version }}.tgz
  sha1: 7220a9bc9c766cb513007f313b804d88f110c228

  # The next lapack version will have a fix for this.
  patches:
    - python-test.patch

build:
  number: 1

requirements:
  build:
    - cmake
    - {{ compiler('fortran') }}        # [unix]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - cloog 0.18.0 10  # [unix]
  run:

test:
  commands:
    - test -f ${PREFIX}/lib/liblapack.so  # [linux]
    - test -f ${PREFIX}/lib/liblapack.dylib  # [osx]
    - if not exist %LIBRARY_PREFIX%\\lib\\liblapack.a exit 1  # [win]

about:
  home: http://www.netlib.org/lapack
  license: BSD 3-Clause
  summary: Linear Algebra PACKage

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - hadim
