{% set version = "3.7.1" %}

package:
  name: lapack
  version: {{ version }}

source:
  fn: lapack-{{ version }}.tgz
  url: http://www.netlib.org/lapack/lapack-{{ version }}.tgz
  sha1: 84c4f7163b52b1bf1f6ca2193f6f48ed3dec0fab

  # The next lapack version will have a fix for this.
  patches:
    - python-test.patch

build:
  number: 0

requirements:
  build:
    - toolchain
    - cmake
    - gcc  # [unix]
    - cloog 0.18.0 10  # [unix]
    - m2w64-toolchain  # [win]
  run:
    - libgfortran  # [not win]
    - m2w64-gcc-libs  # [win]

test:
  commands:
    - test -f ${PREFIX}/lib/liblapack.so  # [linux]
    - test -f ${PREFIX}/lib/liblapack.dylib  # [osx]
    - if not exist %LIBRARY_PREFIX%\\lib\\liblapack.a exit 1  # [win]

about:
  home: http://www.netlib.org/lapack
  license: BSD 3-Clause
  summary: Linear Algebra PACKage

extra:
  recipe-maintainers:
    - jakirkham
    - jschueller
    - hadim
