travis:
  secure:
    BINSTAR_TOKEN: ig/DaXMIaGM8jX8xIDKcXrAJESAkhN/kMyS2tXk/igNIkVewd539U21UhlikZB4Gf5bVh+dR5TDza8YF1pFjwz0xBWwknmXr8HgoN1YXAJBFHtbgpyLvA5OfGmN1BnQ9U/LjLR6XLOFQbXJd3MoO0KF/eZPdDLP9FXdOW3jeWvlIi1xOGq6YKS0IkBjVgyDQtCOPt2rk5J7Ji1Ax/EQwdAt28uhgrRnrydyy1bWuz2ny6D+3iM51ZDoDISc/8a5zI/qhdvfLtoDiDtzSUcj3YtE7RE2rfrxH7M7cXz4kzM3nDpklY1NaWZ3YjSD5DPaRCi0qG3/DjDty1mz/dPqp31MAbtWsuC/9zY2fuZ4LxOe9rRDs/9sTaeG7k5FGg8ZvdByE/HyB4LthhCsbMH1tiVUXJa/d/Jmd7SKbGOQavBnVllffds6gbrG4+0W/h9wy5+NAq7C9bap2Fdn44Lm0Ifn1xKyr92CIN2Orc1i8XUS06JpGSrCzqAiEpvLHpZdbn+5rIYGQ4wuEL/O2f8OXk8++FdmA3krqpuHNG2iwXYgz5LYQDbV9BaijFWYk52yh2q35n/pqkBscv4VJNnSfGiTTVgxhxluw/FbOMWfkM1GEsDL6i5z5w3ycD3+avmyox0/YcSRT9qdcqbIgXFJAsjeddARUeoQ76/8ajNdphlo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1

compiler_stack: comp7
